### ISSUE TITLE
ttycast behind apache?

### ISSUE THREAD

**Issue by smblott-github** [dtinth/ttycast#13]
This isn't really and issue, more a question...

`ttycast` doesn't seem to play nicely behind an Apache reverse proxy:

- there's no way to set a path prefix for all links, and
- even after much hacking, I can't get the websocket connection to go through Apache unless it's at the root of the path space.

Is there an approved way of doing this kind of thing?

(Also, is this project alive?  All of the issues seem kind of old.)

Thanks!

**Comment by dtinth** [comment]
Hello, and thanks for your interest in this project.

Unfortunately, ttycast isn’t designed to be used behind a reverse proxy that changes paths. This is so that the code becomes as simple as it can get.

`ttycast` is created with only several hundred lines of code. Please feel free to clone the code and modify it to suit your needs.

Another easy solution is to use subdomains instead.

**Comment by smblott-github** [comment]
Thanks, @dtinth.
